export const LOADING = "LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const NOTIFICATION_MESSAGE = "NOTIFICATION_MESSAGE";
export const CLOSE_NOTIFICATION = "CLOSE_NOTIFICATION";
export const OPEN_BACKDROP = "OPEN_BACKDROP";
export const CLOSE_BACKDROP = "CLOSE_BACKDROP";
